export type LotrCardKeywords =
  | 'Archer'
  | 'Battleground'
  | 'Besieger'
  | 'Corsair'
  | 'Dwelling'
  | 'Easterling'
  | 'Enduring'
  | 'Engine'
  | 'Fierce'
  | 'Forest'
  | 'Fortification'
  | 'Hunter'
  | 'Knight'
  | 'Lurker'
  | 'Machine'
  | 'Marsh'
  | 'Mountain'
  | 'Muster'
  | 'Pipeweed'
  | 'Plains'
  | 'Ranger'
  | 'Ring-bound'
  | 'River'
  | 'Search'
  | 'Southron'
  | 'Spell'
  | 'Stealth'
  | 'Tale'
  | 'Tentacle'
  | 'Tracker'
  | 'Twilight'
  | 'Underground'
  | 'Unhasty'
  | 'Valiant'
  | 'Villager'
  | 'Warg-rider'
  | 'Weather'
  | 'Wise';

export const lotrCardKeywordTypeMappings: Record<LotrCardKeywords, string> = {
  Archer: '',
  Battleground: 'BATTLEGROUND',
  Besieger: 'BESIEGER',
  Corsair: 'CORSAIR',
  Dwelling: 'DWELLING',
  Easterling: 'EASTERLING',
  Enduring: 'ENDURING',
  Engine: 'ENGINE',
  Fierce: 'FIERCE',
  Forest: 'FOREST',
  Fortification: 'FORTIFICATION',
  Hunter: 'HUNTER',
  Knight: 'KNIGHT',
  Lurker: 'LURKER',
  Machine: 'MACHINE',
  Marsh: 'MARSH',
  Mountain: 'MOUNTAIN',
  Muster: 'MUSTER',
  Pipeweed: 'PIPEWEED',
  Plains: 'PLAINS',
  Ranger: 'RANGER',
  'Ring-bound': 'RING_BOUND',
  River: 'RIVER',
  Search: 'SEARCH',
  Southron: 'SOUTHRON',
  Spell: 'SPELL',
  Stealth: 'STEALTH',
  Tale: 'TALE',
  Tentacle: 'TENTACLE',
  Tracker: 'TRACKER',
  Twilight: 'TWILIGHT',
  Underground: 'UNDERGROUND',
  Unhasty: 'UNHASTY',
  Valiant: 'VALIANT',
  Villager: 'VILLAGER',
  'Warg-rider': 'WARG_RIDER',
  Weather: 'WEATHER',
  Wise: 'WISE',
};
